/**
 * Contact management REST API
 * API
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * Contact: pasquale.paola@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ErrorMessage { 
    message?: string;
}
