


CREATE TABLE CONTACTS (
  id INT PRIMARY KEY ,
  NAME VARCHAR(32),
  PROVINCIA VARCHAR(25),
  COMUNE  VARCHAR(25),
  SURNAME VARCHAR(32),
  BIRTH_DATE DATE,
  NATION VARCHAR(20),
  SEX VARCHAR(1),
  FISCAL_CODE VARCHAR(50),
  PHONE VARCHAR(20),
  EMAIL VARCHAR(50)
);