


CREATE TABLE CONTACTS (
  id INT IDENTITY PRIMARY KEY ,
  FIRST_NAME VARCHAR(32),
  LAST_NAME VARCHAR(25),
  BIRTH_PLACE  VARCHAR(25),
  BIRTH_DATE DATE,
  COUNTRY VARCHAR(32),
  GENDER VARCHAR(1),
  PHONE VARCHAR(20),
  EMAIL VARCHAR(50),
  ADDRESS VARCHAR(200),
  TIME timestamp default 'now'
);