
INSERT INTO CONTACTS (
  FIRST_NAME,
  LAST_NAME,
  BIRTH_PLACE  ,
  BIRTH_DATE ,
  COUNTRY,
  GENDER ,
  PHONE ,
  EMAIL,
   ADDRESS) VALUES ('PASQUALE','PAOLA','Pompei',DATE '1981-06-25','ITALY','M','1234567891','paspao@pao.it','VIA ROMA, POMPEI');

