
INSERT INTO CONTACTS (id ,
  NAME,
  PROVINCIA,
  COMUNE  ,
  SURNAME ,
  BIRTH_DATE,
  NATION ,
  SEX ,
  FISCAL_CODE ,
  PHONE ,
  EMAIL ) VALUES (1,'PASQUALE','Napoli','Pompei','PAOLA',DATE '1981-06-25','ITALY','M','PLAPPP22G33T543Z','1234567891','paspao@pao.it');

